\
import os
import subprocess
import tempfile
import shutil
import uuid
import json # Added
from typing import Optional, Dict, Any, List # Added
from ..base_agent import BaseAgent

class CodeExecutionAgent(BaseAgent):
    """
    An agent that executes Python code snippets or scripts in a sandboxed Docker environment.
    It can run arbitrary Python code strings (e.g., for analysis) or full Python script files (e.g., main simulations).
    It detects output artifacts, creates manifests, and summarizes execution.
    """
    def __init__(self, 
                 docker_image_name: str, 
                 model: str = "gpt-4.1", 
                 memory_manager=None, 
                 iteration: int = 0, 
                 output_dir: Optional[str] = None, # For agent's own direct outputs (e.g., internal logs if any)
                 goal: str = None, 
                 role: str = None, 
                 expertise: str = None):
        super().__init__(
            title="Code Execution Agent",
            expertise=expertise or "Secure Python Code Execution and Script Management in Docker",
            goal=goal or "Execute provided Python code/scripts in an isolated Docker environment, manage artifacts, and return results.",
            role=role or "Secure Code and Script Executor",
            model=model
        )
        self.docker_image_name = docker_image_name
        self.memory_manager = memory_manager
        self.iteration = iteration
        # self.output_dir is for the CodeExecutionAgent's own direct outputs, 
        # NOT for the artifacts generated by the scripts it runs.
        # Artifacts from executed scripts go into paths specified during method calls.
        self.agent_output_dir = output_dir or os.path.join(os.getcwd(), "code_execution_agent_outputs")
        os.makedirs(self.agent_output_dir, exist_ok=True)

    def _file_type_and_desc(self, path: str) -> tuple[str, str]:
        ext = os.path.splitext(path)[1].lower()
        if ext == '.csv':
            return 'csv', 'CSV data file'
        elif ext == '.pkl':
            return 'pickle', 'Pickle data file'
        elif ext in ['.png', '.jpg', '.jpeg', '.svg', '.gif']:
            return 'image', 'Figure/image file'
        elif ext == '.json':
            return 'json', 'JSON data file'
        elif ext == '.txt' or ext == '.md':
            return 'text', 'Text or Markdown file'
        else:
            return ext[1:] if ext else 'unknown', 'Other file'

    def _collect_new_files_recursive(self, base_dir: str, before_set: set) -> List[str]:
        new_files = []
        # Ensure base_dir exists before walking
        if not os.path.isdir(base_dir):
            print(f"Warning: Output directory {base_dir} does not exist for artifact collection.")
            return new_files
        for root, _, files_in_root in os.walk(base_dir):
            for f_name in files_in_root:
                full_path = os.path.join(root, f_name)
                if full_path not in before_set:
                    new_files.append(os.path.abspath(full_path))
        return new_files

    def execute_code_string_in_docker(self,
                                   code_string: str,
                                   input_data_directory_on_host: Optional[str] = None,
                                   internal_input_dir_in_container: str = "/app/inputs",
                                   output_dir_on_host_for_artifacts: Optional[str] = None,
                                   internal_output_dir_in_container: str = "/app/outputs",
                                   expected_output_filenames_in_script: Optional[List[str]] = None) -> Dict[str, Any]:
        """
        Executes the given Python code string in a Docker container.
        Designed for analysis snippets that might read from an input dir and write to an output dir.

        Args:
            code_string: The Python code to execute.
            input_data_directory_on_host: Absolute path to a directory on the host containing input files.
                                          This directory will be mounted to `internal_input_dir_in_container`.
            internal_input_dir_in_container: Path inside the container where inputs will be available.
            output_dir_on_host_for_artifacts: Absolute path on the host where generated artifacts should be saved.
                                               This directory will be mounted to `internal_output_dir_in_container`.
            internal_output_dir_in_container: Path inside the container where the script should write outputs.
            expected_output_filenames_in_script: Optional list of filenames the script is expected to generate
                                                 relative to `internal_output_dir_in_container`. If None, all new files are collected.

        Returns:
            A dictionary containing success, stdout, stderr, error_message, and paths to artifacts.
        """
        result = {
            "status": "failed", # Changed from "success" to "status" for consistency
            "stdout": "",
            "stderr": "",
            "artifacts_host_generated": [], # List of absolute paths on host
            "error_message": ""
        }
        
        temp_script_dir_host = tempfile.mkdtemp(prefix="code_exec_string_")
        script_filename_host = os.path.join(temp_script_dir_host, "script_to_execute.py")

        # Ensure output directory for artifacts exists on host if specified
        if output_dir_on_host_for_artifacts:
            os.makedirs(output_dir_on_host_for_artifacts, exist_ok=True)
        
        # Collect files in output_dir_on_host_for_artifacts before execution
        before_output_files = set()
        if output_dir_on_host_for_artifacts:
            for root, _, files_in_root in os.walk(output_dir_on_host_for_artifacts):
                for f_name in files_in_root:
                    before_output_files.add(os.path.join(root, f_name))

        try:
            with open(script_filename_host, "w") as f:
                f.write(code_string)

            docker_command = ["docker", "run", "--rm"]
            
            # Mount the script itself
            docker_command.extend(["-v", f"{os.path.abspath(script_filename_host)}:{internal_input_dir_in_container}/script_to_execute.py:ro"])
            
            # Mount input directory if provided
            if input_data_directory_on_host and os.path.exists(input_data_directory_on_host):
                docker_command.extend(["-v", f"{os.path.abspath(input_data_directory_on_host)}:{internal_input_dir_in_container}:ro"])
            
            # Mount output directory if provided
            if output_dir_on_host_for_artifacts:
                docker_command.extend(["-v", f"{os.path.abspath(output_dir_on_host_for_artifacts)}:{internal_output_dir_in_container}"])
            
            # Set working directory
            docker_command.extend(["-w", internal_input_dir_in_container]) # Script is here, inputs might be too
            
            docker_command.extend([self.docker_image_name, "python", "script_to_execute.py"])

            process = subprocess.run(docker_command, capture_output=True, text=True, timeout=3000)
            result["stdout"] = process.stdout
            result["stderr"] = process.stderr

            if process.returncode == 0:
                result["status"] = "success"
                if output_dir_on_host_for_artifacts:
                    if expected_output_filenames_in_script:
                        for fname in expected_output_filenames_in_script:
                            host_path = os.path.join(output_dir_on_host_for_artifacts, fname)
                            if os.path.exists(host_path):
                                result["artifacts_host_generated"].append(os.path.abspath(host_path))
                    else: # Collect all new files
                        result["artifacts_host_generated"] = self._collect_new_files_recursive(output_dir_on_host_for_artifacts, before_output_files)
            else:
                result["error_message"] = f"Docker execution failed (code string). RC: {process.returncode}. Stderr: {process.stderr}"
                result["status"] = "failed_execution"

        except subprocess.TimeoutExpired:
            result["error_message"] = "Docker execution (code string) timed out."
            result["stderr"] = "Timeout occurred after 300 seconds."
            result["status"] = "failed_timeout"
        except Exception as e:
            result["error_message"] = f"An unexpected error occurred (code string): {str(e)}"
            result["status"] = "failed_exception"
        finally:
            if os.path.exists(temp_script_dir_host):
                shutil.rmtree(temp_script_dir_host)
        
        if self.memory_manager:
            mem_summary = f"Code string execution. Status: {result['status']}."
            if result['status'] == 'success':
                mem_summary += f" Artifacts: {len(result['artifacts_host_generated'])}."
            else:
                mem_summary += f" Error: {result['error_message'][:100]}..."
            
            # Call write_memory with appropriate arguments
            self.memory_manager.write_memory(
                iteration=self.iteration,
                agent=self.title,
                summary=mem_summary,
                # output_file can be None or a relevant path if applicable
                # For string execution, there isn't a single primary output file like a manifest
                # So, we can pass None or a path to the agent's own log if desired.
                # For now, let's pass None.
                output_file=None 
            )
            # If you have other metadata specific to this memory entry that UnifiedChromaMemoryManager
            # is designed to store beyond the core fields, you would handle it according to its design.
            # The current UnifiedChromaMemoryManager.write_memory takes specific args and then uses
            # a 'metadatas' field in collection.upsert for 'iteration' and 'agent'.
            # If more complex metadata needs to be stored and searchable, UnifiedChromaMemoryManager might need adjustment
            # or the information should be part of the 'summary'.

        return result

    def execute_script_in_docker(self,
                                script_file_path_on_host: str,
                                script_args: Optional[List[str]] = None,
                                host_output_dir_for_script_artifacts: str = "./script_outputs", # Where script\'s primary outputs go
                                internal_output_dir_in_container: str = "/app/outputs", # Script writes here
                                host_input_dir_for_script: Optional[str] = None, # Optional: if script needs to read from a dir
                                internal_input_dir_in_container: str = "/app/inputs"  # Script reads from here
                                ) -> Dict[str, Any]:
        """
        Executes a Python script file in a Docker container.
        This is intended for running main simulation scripts.

        Args:
            script_file_path_on_host: Absolute path to the Python script on the host.
            script_args: List of arguments to pass to the script. IMPORTANT: If the script
                         needs to write to its output directory, an argument like
                         `--output_base_dir /app/outputs` (matching internal_output_dir_in_container)
                         MUST be included in script_args by the caller.
            host_output_dir_for_script_artifacts: Directory on the host where the script\'s generated files will appear.
                                                 This dir is mounted to `internal_output_dir_in_container`.
            internal_output_dir_in_container: Path inside the container where the script should write its outputs.
            host_input_dir_for_script: Optional. Directory on host with input data for the script.
            internal_input_dir_in_container: Path inside container where script can find input data.

        Returns:
            Dictionary with success, stdout, stderr, error, manifest_path, message_to_analysis_agent.
        """
        result = {
            "success": False, 
            "stdout": None, 
            "stderr": None, 
            "error": None, 
            "manifest_path": None,
            "message_to_analysis_agent": "",
            "artifacts_host_generated": [] # For internal tracking, not primary part of old ExecutorAgent return
        }

        if not os.path.exists(script_file_path_on_host):
            result["error"] = f"Script file not found: {script_file_path_on_host}"
            return result

        # Ensure the script's target output directory on the host exists
        os.makedirs(host_output_dir_for_script_artifacts, exist_ok=True)
        
        # Path for the script inside the container (we'll mount its directory)
        script_dir_on_host = os.path.dirname(script_file_path_on_host)
        script_filename = os.path.basename(script_file_path_on_host)
        internal_script_path_in_container = f"/app/script_code/{script_filename}" # Mount script to a specific sub-dir

        # Collect files in output_dir_on_host_for_script_artifacts before execution
        before_script_output_files = set()
        for root, _, files_in_root in os.walk(host_output_dir_for_script_artifacts):
            for f_name in files_in_root:
                before_script_output_files.add(os.path.join(root, f_name))

        docker_command = ["docker", "run", "--rm"]
        
        # Mount script's directory (read-only)
        docker_command.extend(["-v", f"{os.path.abspath(script_dir_on_host)}:/app/script_code:ro"])
        
        # Mount output directory (read-write)
        docker_command.extend(["-v", f"{os.path.abspath(host_output_dir_for_script_artifacts)}:{internal_output_dir_in_container}"])

        # Mount input directory if provided (read-only)
        if host_input_dir_for_script and os.path.isdir(host_input_dir_for_script):
            docker_command.extend(["-v", f"{os.path.abspath(host_input_dir_for_script)}:{internal_input_dir_in_container}:ro"])

        # Set working directory (can be where outputs go, or where script is, depending on script's relative path usage)
        # Let's use the script's directory as CWD in container for simplicity if script uses relative paths for its own modules.
        docker_command.extend(["-w", "/app/script_code"]) 
        
        docker_command.append(self.docker_image_name)
        docker_command.append("python")
        docker_command.append(script_filename) # script_filename is now relative to /app/script_code
        
        if script_args:
            docker_command.extend(script_args)
        
        try:
            proc = subprocess.run(docker_command, capture_output=True, text=True) #timeout=6000)
            result["stdout"] = proc.stdout
            result["stderr"] = proc.stderr

            if proc.returncode != 0:
                result["success"] = False
                result["error"] = proc.stderr
            else:
                result["success"] = True

            # Collect new files from the script's output directory on the host
            new_files_host_paths = self._collect_new_files_recursive(host_output_dir_for_script_artifacts, before_script_output_files)
            result["artifacts_host_generated"] = new_files_host_paths # Store absolute paths

            # --- Create manifest file in host_output_dir_for_script_artifacts ---
            manifest_entries = []
            for f_abs_path in new_files_host_paths:
                ftype, desc = self._file_type_and_desc(f_abs_path)
                manifest_entries.append({"path": f_abs_path, "type": ftype, "description": desc})
            
            summary_for_manifest = f"Ran {script_filename} with args {' '.join(script_args) if script_args else 'N/A'}; created {len(new_files_host_paths)} new files in {host_output_dir_for_script_artifacts}."
            manifest_dict = {"files": manifest_entries, "summary": summary_for_manifest, "script_args": script_args if script_args else []}
            
            # Manifest is saved to the script's output directory on the host
            manifest_path_on_host = os.path.join(host_output_dir_for_script_artifacts, "run_manifest.json") 
            with open(manifest_path_on_host, "w") as mf:
                json.dump(manifest_dict, mf, indent=2)
            result["manifest_path"] = os.path.abspath(manifest_path_on_host)

            # --- Generate message_to_analysis_agent (LLM summary) ---
            with open(script_file_path_on_host, 'r') as f:
                script_content_for_llm = f.read()

            context_prompt = (
                f"You are an expert simulation runner and summarizer.\n"
                f"You have just overseen the execution of the following experiment script in a Docker container: {script_filename}\n"
                f"With arguments: {script_args if script_args else 'None'}\n"
                f"The script was configured to output files to a directory mapped to the host at: {host_output_dir_for_script_artifacts}\n"
                f"Your job is to provide a concise, high-level summary of what was simulated (e.g., the biological or modeling context, such as T cell interactions with tumors),\n"
                f"and enumerate all output files generated, including their paths and types.\n"
                f"You do NOT need to include stdout or stderr unless there was a critical error.\n"
                f"\n"
                f"Script content (for context):\n{script_content_for_llm[:2000]}\n" # Truncate for prompt
                f"\n"
                f"Manifest of generated files (absolute paths on host) from {host_output_dir_for_script_artifacts}:\n{json.dumps(manifest_entries, indent=2)}\n"
                f"\n"
                f"If possible, infer the overall purpose of the experiment from the script.\n"
                f"Summarize in a way that is useful for a downstream analysis agent."
            )
            if self.model and self.client: # Check if LLM capabilities are configured
                llm_response = self.client.chat.completions.create(
                    model=self.model,
                    messages=[{"role": "user", "content": context_prompt}],
                    max_tokens=4000 # Adjusted
                )
                result["message_to_analysis_agent"] = llm_response.choices[0].message.content
            else:
                result["message_to_analysis_agent"] = f"LLM summarization skipped (model not configured). Basic summary: {summary_for_manifest}"


            # --- Memory Logging ---
            if self.memory_manager:
                short_summary_for_memory = result["message_to_analysis_agent"] # Use LLM summary if available
                if not self.model or not self.client: # Fallback if LLM not used
                    short_summary_for_memory = summary_for_manifest
                
                # Truncate if too long for memory
                if len(short_summary_for_memory) > 2000:
                     short_summary_for_memory = short_summary_for_memory[:1997] + "..."

                self.memory_manager.write_memory(
                    iteration=self.iteration,
                    agent=self.title,
                    summary=short_summary_for_memory,
                    output_file=result["manifest_path"] # Manifest path is a good candidate for output_file
                )
                # Additional metadata that was previously in the 'metadata' dict for add_memory
                # like executed_script, script_arguments, etc., if they need to be stored,
                # should either be part of the 'summary' or UnifiedChromaMemoryManager
                # would need to be adapted to store them explicitly in its ChromaDB structure.
                # For now, the primary information is in the summary and the manifest_path.
        
        except subprocess.TimeoutExpired:
            result["success"] = False
            result["error"] = "Docker execution (script) timed out."
            result["stderr"] = "Timeout occurred after 600 seconds."
        except Exception as e:
            result["success"] = False
            result["error"] = f"An unexpected error occurred (script execution): {str(e)}"
        
        if not result["success"] and self.memory_manager: # Log errors to memory
             error_summary = f"Error executing script {script_file_path_on_host} with args {script_args if script_args else 'None'}: {result['error']}"
             
             self.memory_manager.write_memory(
                 iteration=self.iteration,
                 agent=self.title,
                 summary=error_summary[:2000], # Truncate
                 # No specific output file for an error, can pass None
                 output_file=None 
             )
             # Similar to above, other details like script_arguments for errors
             # would need to be part of the summary or handled by an adapted UnifiedChromaMemoryManager.
        return result

# Example Usage (Illustrative - requires Docker and a built image 'code-execution-env')
if __name__ == '__main__':
    # This example won't run directly without setting up a dummy script, Docker, etc.
    # It's for conceptual understanding.

    # --- Example for execute_code_string_in_docker ---
    # print("\\n--- Testing execute_code_string_in_docker ---")
    # agent_string_executor = CodeExecutionAgent(docker_image_name="code-execution-env", model=None) # No LLM for this agent usually
    
    # # Create dummy input dir and file for string execution
    # dummy_host_input_dir_string = tempfile.mkdtemp(prefix="dummy_string_input_")
    # dummy_host_output_dir_string = tempfile.mkdtemp(prefix="dummy_string_output_")
    # with open(os.path.join(dummy_host_input_dir_string, "data.csv"), "w") as f:
    #     f.write("id,value\\n1,10\\n2,20")

    # code_to_run_string = \'\'\'
# import pandas as pd
# import os
# print(f"Script internal input dir: /app/inputs")
# print(f"Script internal output dir: /app/outputs")
# print(f"Files in input dir: {os.listdir(\'/app/inputs\')}")
# df = pd.read_csv(\'/app/inputs/data.csv\')
# df[\'new_value\'] = df[\'value\'] * 2
# df.to_csv(\'/app/outputs/processed_data.csv\', index=False)
# print(\'String script finished.\')
# \'\'\'
    # string_exec_result = agent_string_executor.execute_code_string_in_docker(
    #     code_string=code_to_run_string,
    #     input_data_directory_on_host=dummy_host_input_dir_string,
    #     internal_input_dir_in_container="/app/inputs", # Must match what script expects
    #     output_dir_on_host_for_artifacts=dummy_host_output_dir_string,
    #     internal_output_dir_in_container="/app/outputs", # Must match what script expects
    #     expected_output_filenames_in_script=["processed_data.csv"]
    # )
    # print(json.dumps(string_exec_result, indent=2))
    # if string_exec_result["status"] == "success" and string_exec_result["artifacts_host_generated"]:
    #     print(f"Generated file content ({string_exec_result['artifacts_host_generated'][0]}):")
    #     with open(string_exec_result['artifacts_host_generated'][0], 'r') as f_out:
    #         print(f_out.read())
    
    # shutil.rmtree(dummy_host_input_dir_string)
    # shutil.rmtree(dummy_host_output_dir_string)


    # --- Example for execute_script_in_docker ---
    # print("\\n\\n--- Testing execute_script_in_docker ---")
    # # Needs a model for summarization, or pass model=None to skip LLM summary
    # agent_script_executor = CodeExecutionAgent(docker_image_name="code-execution-env", model="gpt-3.5-turbo") # or your preferred model
    
    # # Create a dummy script file
    # dummy_script_dir = tempfile.mkdtemp(prefix="dummy_script_")
    # dummy_script_path = os.path.join(dummy_script_dir, "test_simulation.py")
    # dummy_host_output_dir_script = tempfile.mkdtemp(prefix="dummy_script_output_")

    # with open(dummy_script_path, "w") as f:
    #     f.write(\'\'\'
# import argparse
# import os
# import json
# print(\'Test simulation script started.\')
# parser = argparse.ArgumentParser()
# parser.add_argument(\'--output_base_dir\', type=str, required=True)
# parser.add_argument(\'--param\', type=int, default=1)
# args = parser.parse_args()
# print(f\'Script args: {args}\')
# os.makedirs(args.output_base_dir, exist_ok=True)
# data = {\'param\': args.param, \'message\': \'Hello from script!\'}
# with open(os.path.join(args.output_base_dir, \'script_output.json\'), \'w\') as sf:
#     json.dump(data, sf)
# with open(os.path.join(args.output_base_dir, \'another_file.txt\'), \'w\') as tf:
#     tf.write(\'Some text output.\')
# print(\'Test simulation script finished.\')
# \'\'\')

    # script_execution_args = [
    #     "--output_base_dir", "/app/outputs", # This path is INSIDE the container
    #     "--param", "123"
    # ]
    # script_exec_result = agent_script_executor.execute_script_in_docker(
    #     script_file_path_on_host=dummy_script_path,
    #     script_args=script_execution_args,
    #     host_output_dir_for_script_artifacts=dummy_host_output_dir_script, # Host path where outputs will appear
    #     internal_output_dir_in_container="/app/outputs" # Script writes here (maps to host_output_dir_for_script_artifacts)
    # )
    # print(json.dumps(script_exec_result, indent=2))
    # if script_exec_result["success"] and script_exec_result["manifest_path"]:
    #     print(f"Manifest content ({script_exec_result['manifest_path']}):")
    #     with open(script_exec_result['manifest_path'], 'r') as mf_out:
    #         print(mf_out.read())
    
    # shutil.rmtree(dummy_script_dir)
    # shutil.rmtree(dummy_host_output_dir_script)
    pass
